/*
 * Copyright 2014-2015 Project Chronos and Pramantha Ltd
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package uk.projectchronos.xplorationreader.model;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoException;
import uk.projectchronos.xplorationreader.dao.ArticleDao;
import uk.projectchronos.xplorationreader.dao.DaoSession;
import uk.projectchronos.xplorationreader.dao.KeywordDao;
import uk.projectchronos.xplorationreader.dao.KeywordToArticlesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
// TODO use KeepSections http://greendao-orm.com/documentation/modelling-entities

/**
 * Entity mapped to table "ARTICLE".
 */
public class Article {

    /**
     * Id in database.
     */
    private Long id;

    /**
     * Title of the article.
     */
    @Expose
    private String title;

    /**
     * URL to the article.
     */
    @Expose
    private String url;
    /**
     * Abstract (if present, else "" void string).
     */
    @Expose
    @SerializedName("abstract")
    private String _abstract;

    /**
     * URL to the array of keywords connected to this Article object, [] if no keyword.
     */
    @Expose
    @SerializedName("keywords_url")
    private String keywordsUrl;

    /**
     * String for date-time of storage, ISO 8601 format.
     */
    @Expose
    private java.util.Date stored;

    /**
     * Sring for date-time of publishing ISO 8601 format, else null.
     */
    @Expose
    private java.util.Date published;

    /**
     * Used to resolve relations
     */
    private transient DaoSession daoSession;

    /**
     * Used for active entity operations.
     */
    private transient ArticleDao myDao;

    /**
     * List of KeywordsToArticles.
     */
    private List<KeywordToArticles> keywordToArticlesList;

    /**
     * List of Keywords.
     */
    private List<Keyword> keywordsList;

    public Article() {
    }

    public Article(Long id) {
        this.id = id;
    }

    public Article(Long id, String title, String url, String _abstract, String keywordsUrl, java.util.Date stored, java.util.Date published) {
        this.id = id;
        this.title = title;
        this.url = url;
        this._abstract = _abstract;
        this.keywordsUrl = keywordsUrl;
        this.stored = stored;
        this.published = published;
    }

    /**
     * called by internal mechanisms, do not call yourself.
     */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getArticleDao() : null;
    }

    /**
     * Gets the id of the article.
     *
     * @return the id.
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the id of the article.
     *
     * @param id the id to set.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the title of the article.
     *
     * @return the title.
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the title of the article.
     *
     * @param title the title to set.
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Gets the URL of the article.
     *
     * @return the URL of the article.
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the URL of the article.
     *
     * @param url the URL to set.
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * Gets the abastract of the article.
     *
     * @return the abastract of the article.
     */
    public String get_abstract() {
        return _abstract;
    }

    /**
     * Sets the abstract of the article.
     *
     * @param _abstract the abstract to set.
     */
    public void set_abstract(String _abstract) {
        this._abstract = _abstract;
    }

    /**
     * Gets the keywords URL of the article.
     *
     * @return the keywords URL of the article.
     */
    public String getKeywordsUrl() {
        return keywordsUrl;
    }

    /**
     * Sets the keywords URL of the article.
     *
     * @param keywordsUrl the URL of the keywords to set.
     */
    public void setKeywordsUrl(String keywordsUrl) {
        this.keywordsUrl = keywordsUrl;
    }

    /**
     * Gets the stored date of the article.
     *
     * @return the stored date of the article.
     */
    public java.util.Date getStored() {
        return stored;
    }

    /**
     * Sets the stored date of the article.
     *
     * @param stored the stored date to set.
     */
    public void setStored(java.util.Date stored) {
        this.stored = stored;
    }

    /**
     * Gets the publised date of the article.
     *
     * @return the publised date of the article.
     */
    public java.util.Date getPublished() {
        return published;
    }

    /**
     * Sets the published date of the article.
     *
     * @param published the published date to set.
     */
    public void setPublished(java.util.Date published) {
        this.published = published;
    }

    /**
     * To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity.
     */
    public List<KeywordToArticles> getKeywordToArticlesList() {
        if (keywordToArticlesList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            KeywordToArticlesDao targetDao = daoSession.getKeywordToArticlesDao();
            List<KeywordToArticles> keywordToArticlesListNew = targetDao._queryArticle_KeywordToArticlesList(id);
            synchronized (this) {
                if (keywordToArticlesList == null) {
                    keywordToArticlesList = keywordToArticlesListNew;
                }
            }
        }
        return keywordToArticlesList;
    }

    /**
     * Gets keywords of the article.
     *
     * @return the keywords list of the article.
     */
    public List<Keyword> getKeywordsList() {
        if (keywordsList == null) {
            keywordsList = new ArrayList<>();
            for (KeywordToArticles keywordToArticles : getKeywordToArticlesList()) {
                long keywordId = keywordToArticles.getKeywordId();

                keywordsList.addAll(daoSession.getKeywordDao().queryBuilder().where(KeywordDao.Properties.Id.eq(keywordId)).list());
            }
        }
        return keywordsList;
    }

    /**
     * Resets a to-many relationship, making the next get call to query for a fresh result.
     */
    public synchronized void resetKeywordToArticlesList() {
        keywordToArticlesList = null;
    }

    /**
     * Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context.
     */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.delete(this);
    }

    /**
     * Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context.
     */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.update(this);
    }

    /**
     * Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context.
     */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.refresh(this);
    }

    @Override
    public String toString() {
        return "Article{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", url='" + url + '\'' +
                ", _abstract='" + _abstract + '\'' +
                ", keywordsUrl='" + keywordsUrl + '\'' +
                ", stored=" + stored +
                ", published=" + published +
                ", daoSession=" + daoSession +
                ", myDao=" + myDao +
                ", keywordToArticlesList=" + keywordToArticlesList +
                ", keywordsList=" + keywordsList +
                '}';
    }
}