/*
 * Copyright 2014-2015 Project Chronos and Pramantha Ltd
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package uk.projectchronos.xplorationreader.model;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoException;
import uk.projectchronos.xplorationreader.dao.ArticleDao;
import uk.projectchronos.xplorationreader.dao.DaoSession;
import uk.projectchronos.xplorationreader.dao.KeywordDao;
import uk.projectchronos.xplorationreader.dao.KeywordToArticlesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ARTICLE".
 */
public class Article {

    /**
     *
     */
    private Long id;


    /**
     *
     */
    @Expose
    private String title;

    /**
     *
     */
    @Expose
    private String url;
    /**
     *
     */
    @Expose
    @SerializedName("abstract")
    private String _abstract;

    /**
     *
     */
    @Expose
    @SerializedName("keywords_url")
    private String keywordsUrl;

    /**
     *
     */
    @Expose
    private java.util.Date stored;

    /**
     *
     */
    @Expose
    private java.util.Date published;

    /**
     * Used to resolve relations
     */
    private transient DaoSession daoSession;

    /**
     * Used for active entity operations.
     */
    private transient ArticleDao myDao;

    /**
     *
     */
    private List<KeywordToArticles> keywordToArticlesList;

    /**
     *
     */
    private List<Keyword> keywordsList;

    public Article() {
    }

    public Article(Long id) {
        this.id = id;
    }

    public Article(Long id, String title, String url, String _abstract, String keywordsUrl, java.util.Date stored, java.util.Date published) {
        this.id = id;
        this.title = title;
        this.url = url;
        this._abstract = _abstract;
        this.keywordsUrl = keywordsUrl;
        this.stored = stored;
        this.published = published;
    }

    /**
     * called by internal mechanisms, do not call yourself.
     */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getArticleDao() : null;
    }

    /**
     * @return
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return
     */
    public String getTitle() {
        return title;
    }

    /**
     *
     * @param title
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     *
     * @return
     */
    public String getUrl() {
        return url;
    }

    /**
     *
     * @param url
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     *
     * @return
     */
    public String get_abstract() {
        return _abstract;
    }

    /**
     *
     * @param _abstract
     */
    public void set_abstract(String _abstract) {
        this._abstract = _abstract;
    }

    /**
     *
     * @return
     */
    public String getKeywordsUrl() {
        return keywordsUrl;
    }

    /**
     * @param keywordsUrl
     */
    public void setKeywordsUrl(String keywordsUrl) {
        this.keywordsUrl = keywordsUrl;
    }

    /**
     * @return
     */
    public java.util.Date getStored() {
        return stored;
    }

    /**
     *
     * @param stored
     */
    public void setStored(java.util.Date stored) {
        this.stored = stored;
    }

    /**
     *
     * @return
     */
    public java.util.Date getPublished() {
        return published;
    }

    /**
     *
     * @param published
     */
    public void setPublished(java.util.Date published) {
        this.published = published;
    }

    /**
     * To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity.
     */
    public List<KeywordToArticles> getKeywordToArticlesList() {
        if (keywordToArticlesList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            KeywordToArticlesDao targetDao = daoSession.getKeywordToArticlesDao();
            List<KeywordToArticles> keywordToArticlesListNew = targetDao._queryArticle_KeywordToArticlesList(id);
            synchronized (this) {
                if (keywordToArticlesList == null) {
                    keywordToArticlesList = keywordToArticlesListNew;
                }
            }
        }
        return keywordToArticlesList;
    }

    /**
     * @return
     */
    public List<Keyword> getKeywordsList() {
        if (keywordsList == null) {
            keywordsList = new ArrayList<>();
            for (KeywordToArticles keywordToArticles : getKeywordToArticlesList()) {
                long keywordId = keywordToArticles.getKeywordId();

                keywordsList.addAll(daoSession.getKeywordDao().queryBuilder().where(KeywordDao.Properties.Id.eq(keywordId)).list());
            }
        }
        return keywordsList;
    }

    /**
     * Resets a to-many relationship, making the next get call to query for a fresh result.
     */
    public synchronized void resetKeywordToArticlesList() {
        keywordToArticlesList = null;
    }

    /**
     * Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context.
     */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.delete(this);
    }

    /**
     * Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context.
     */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.update(this);
    }

    /**
     * Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context.
     */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.refresh(this);
    }

    @Override
    public String toString() {
        return "Article{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", url='" + url + '\'' +
                ", _abstract='" + _abstract + '\'' +
                ", keywordsUrl='" + keywordsUrl + '\'' +
                ", stored=" + stored +
                ", published=" + published +
                ", daoSession=" + daoSession +
                ", myDao=" + myDao +
                ", keywordToArticlesList=" + keywordToArticlesList +
                ", keywordsList=" + keywordsList +
                '}';
    }
}