/*
 * Copyright 2014-2015 Project Chronos and Pramantha Ltd
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package uk.projectchronos.xplorationreader.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "KEYWORD_TO_ARTICLES".
 */
public class KeywordToArticles {

    /**
     *
     */
    private Long id;

    /**
     *
     */
    private long keywordId;

    /**
     *
     */
    private long articleId;

    public KeywordToArticles() {
    }

    public KeywordToArticles(Long id) {
        this.id = id;
    }

    public KeywordToArticles(Long id, long keywordId, long articleId) {
        this.id = id;
        this.keywordId = keywordId;
        this.articleId = articleId;
    }

    /**
     * @return
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return
     */
    public long getKeywordId() {
        return keywordId;
    }

    /**
     * @param keywordId
     */
    public void setKeywordId(long keywordId) {
        this.keywordId = keywordId;
    }

    /**
     * @return
     */
    public long getArticleId() {
        return articleId;
    }

    /**
     * @param articleId
     */
    public void setArticleId(long articleId) {
        this.articleId = articleId;
    }

    @Override
    public String toString() {
        return "KeywordToArticles{" +
                "id=" + id +
                ", keywordId=" + keywordId +
                ", articleId=" + articleId +
                '}';
    }
}