/*
 * Copyright 2014-2015 Project Chronos and Pramantha Ltd
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package uk.projectchronos.xplorationreader.model;

import com.google.gson.annotations.Expose;

import java.util.ArrayList;
import java.util.List;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoException;
import uk.projectchronos.xplorationreader.dao.ArticleDao;
import uk.projectchronos.xplorationreader.dao.DaoSession;
import uk.projectchronos.xplorationreader.dao.KeywordDao;
import uk.projectchronos.xplorationreader.dao.KeywordToArticlesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
// TODO use KeepSections http://greendao-orm.com/documentation/modelling-entities

/**
 * Entity mapped to table "KEYWORD".
 */
public class Keyword {

    /**
     * Id in database.
     */
    private Long id;

    /**
     * RelatedUrls ot the keyword.
     */
    @Expose
    private String relatedUrls;

    /**
     * Slug of the keyword.
     */
    @Expose
    private String slug;

    /**
     * Value of the keyword.
     */
    @Expose
    private String value;

    /**
     * Used to resolve relations.
     */
    private transient DaoSession daoSession;

    /**
     * Used for active entity operations.
     */
    private transient KeywordDao myDao;

    /**
     * List of KeywordsToArticles.
     */
    private List<KeywordToArticles> keywordToArticlesList;

    /**
     * List of Article binded to the keyword.
     */
    private List<Article> articlesList;

    public Keyword() {
    }

    public Keyword(Long id) {
        this.id = id;
    }

    public Keyword(Long id, String relatedUrls, String slug, String value) {
        this.id = id;
        this.relatedUrls = relatedUrls;
        this.slug = slug;
        this.value = value;
    }

    /**
     * called by internal mechanisms, do not call yourself.
     */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getKeywordDao() : null;
    }

    /**
     * Gets the id of the keyword.
     *
     * @return the id of the keyword.
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the id of the keyword.
     *
     * @param id the id of the keyword.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the related URL of the keyword.
     *
     * @return the related URL of the keyword.
     */
    public String getRelatedUrls() {
        return relatedUrls;
    }

    /**
     * Sets the related URL of the keyword.
     *
     * @param relatedUrls the related URL of the keyword.
     */
    public void setRelatedUrls(String relatedUrls) {
        this.relatedUrls = relatedUrls;
    }

    /**
     * Gets the slug of the keyword.
     *
     * @return the slug of the keyword.
     */
    public String getSlug() {
        return slug;
    }

    /**
     * Sets the slug of the keyword.
     *
     * @param slug the slug to set.
     */
    public void setSlug(String slug) {
        this.slug = slug;
    }

    /**
     * Gets the value of the keyword.
     *
     * @return the value of the keyword.
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the keyword.
     *
     * @param value the value to set.
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity.
     */
    public List<KeywordToArticles> getKeywordToArticlesList() {
        if (keywordToArticlesList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            KeywordToArticlesDao targetDao = daoSession.getKeywordToArticlesDao();
            List<KeywordToArticles> keywordToArticlesListNew = targetDao._queryKeyword_KeywordToArticlesList(id);
            synchronized (this) {
                if (keywordToArticlesList == null) {
                    keywordToArticlesList = keywordToArticlesListNew;
                }
            }
        }
        return keywordToArticlesList;
    }

    /**
     * Gets the articles binded to the keyword.
     *
     * @return the articles list of the keyword.
     */
    public List<Article> getArticlesList() {
        if (articlesList == null) {
            articlesList = new ArrayList<>();
            for (KeywordToArticles keywordToArticles : getKeywordToArticlesList()) {
                long articleId = keywordToArticles.getArticleId();

                articlesList.addAll(daoSession.getArticleDao().queryBuilder().where(ArticleDao.Properties.Id.eq(articleId)).list());
            }
        }
        return articlesList;
    }

    /**
     * Resets a to-many relationship, making the next get call to query for a fresh result.
     */
    public synchronized void resetKeywordToArticlesList() {
        keywordToArticlesList = null;
    }

    /**
     * Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context.
     */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.delete(this);
    }

    /**
     * Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context.
     */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.update(this);
    }

    /**
     * Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context.
     */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.refresh(this);
    }

    @Override
    public String toString() {
        return "Keyword{" +
                "id=" + id +
                ", relatedUrls='" + relatedUrls + '\'' +
                ", slug='" + slug + '\'' +
                ", value='" + value + '\'' +
                ", daoSession=" + daoSession +
                ", myDao=" + myDao +
                ", keywordToArticlesList=" + keywordToArticlesList +
                ", articlesList=" + articlesList +
                '}';
    }
}